# This file is generated by the scaffold script below.
# Replace or extend as you iterate—keep it simple and readable.

import os
import pandas as pd
import matplotlib.pyplot as plt

os.makedirs("reports/tables", exist_ok=True)
os.makedirs("reports/figures", exist_ok=True)

df = pd.read_csv("data/sample/population.csv")
df = df.sort_values(["country","year"])
df["yoy_growth_pct"] = df.groupby("country")["population"].pct_change() * 100
df.to_csv("reports/tables/population_with_growth.csv", index=False)

one = df[df["country"]=="Aland"]
plt.figure()
plt.plot(one["year"], one["population"], marker="o")
plt.title("Population — Aland (sample)")
plt.xlabel("year"); plt.ylabel("population")
plt.tight_layout()
plt.savefig("reports/figures/aland_trend.png", dpi=160)
print("Wrote reports/tables/population_with_growth.csv and reports/figures/aland_trend.png")

